apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment
  labels:
    app: messaging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
        - name: messaging-app
          image: your-dockerhub-username/messaging_app-web:latest
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_DB
              value: "messaging_db"
            - name: MYSQL_USER
              value: "messaging_user"
            - name: MYSQL_PASSWORD
              value: "messaging_password"
            - name: MYSQL_ROOT_PASSWORD
              value: "root_password"
            - name: DB_HOST
              value: "messaging-app-db"
            - name: DB_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

