pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = 'github-creds'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: "${env.GITHUB_CREDENTIALS}", url: 'https://github.com/Shantralee-58/alx-backend-python.git', branch: 'master'
            }
        }

        stage('Install Dependencies') {
    steps {
        sh 'python -m venv venv'
        sh 'venv\\Scripts\\activate && pip install -r messaging_app/requirements.txt'
    }
}

stage('Run Tests') {
    steps {
        sh 'venv\\Scripts\\activate && pytest --junitxml=report.xml'
    }
    post {
        always {
            junit 'report.xml'
        }
    }
}

